### PR TITLE
[TECH-442] Remove hostport from deployment

### PR DESCRIPTION
**Pull request by koeves**
branch: feature/TECH-442_remove_hostport

### CODE REVIEW

**Review by Jorg88 — APPROVED** [review]
I think it's good if @jddunbarVDB tests this version of mpyl on his monorepo pr before we merge

**Comment by koeves** [comment]
> I'll try re-deploying again sometime this afternoon probably.
> 
> How do I use this version of MPyL for that? @koeves @Jorg88

There's now a test version of MPyL with version `130.1405` that includes this change. If you go to the monorepo MPyL Pipeline, then use this version _and_ select TEST, then you will run the deployment with this version.
Or from the cli: `mpyl build jenkins --test 130.1405`

**Comment by jddunbarVDB** [comment]
> 130.1405

Thanks, that worked and I was able to redeploy my PR: https://jenkins.k8s-serv-backend.vdbinfra.nl/view/MPyL/job/MPyL%20Pipeline/view/change-requests/job/PR-10524/7/

The `keycloak` pod wasn't updated, but the Nginx one was and it seems valid now. The pod started up fine, and there is no reference to `hostPort` in the pod spec. Guess this PR is good to merge!

**Review by jddunbarVDB — APPROVED** [review]
I was able to re-deploy my PR https://jenkins.k8s-serv-backend.vdbinfra.nl/view/MPyL/job/MPyL%20Pipeline/view/change-requests/job/PR-10524/7/ using this build and it seems to work fine without the hostport.

**Pull request merged**
