### PR TITLE
Use black formatter

### PR DESCRIPTION
**Pull request by koeves**
- Reformat codebase with [black](https://github.com/psf/black) formatter

Steps to reproduce:
- Install black with: `pip install black`
- In the root of the repo: `black .`

Resources:
- Add as pycharm external tool: follow https://black.readthedocs.io/en/stable/integrations/editors.html#as-external-tool
- Use black to check formatting with github actions: https://black.readthedocs.io/en/stable/integrations/github_actions.html
- How to introduce black without messing up `git blame`: https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html

### CODE REVIEW

**Review by SamTheisens — CHANGES_REQUESTED** [review]
Looks a lot better 👍. Maybe you could:
 - validate formatting in github action
 - explain that we use black in the documentation. You can also add this badge:
 ```
 <a href="https://github.com/psf/black"><img alt="Code style: black" src="https://img.shields.io/badge/code%20style-black-000000.svg"></a>
 ```

**Comment by koeves** [comment]
> Looks a lot better 👍. Maybe you could:
> 
> * validate formatting in github action
> * explain that we use black in the documentation. You can also add this badge:
> 
> ```
> <a href="https://github.com/psf/black">Code style: black</a>
> ```

What should we do with pylint?

**Comment by SamTheisens** [comment]
> 

Do we need to do anything? Does it clash with black? I guess there's _some_ overlap, but pylint checks more than just formatting.

**Comment by Jorg88** [comment]
Really like it! About pylint: can't we just update our rules to match with black?

**Pull request closed without merging**
